---
title: "How to make a website for github"
author: "Jeff Falke"
date: "October 17, 2018"
output: html_document:
  toc: yes
  toc_float: yes
  number_sections: yes
  theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Libraries

```{r, warning=FALSE,message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(leaflet)
```

#Loading the data

Load the data from KNB
[data](https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e)

```{r}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method = "libcurl"), stringsAsFactors = FALSE)
head(esc)
```
#Pull out median annual escapement by species

```{r}
escapement <- esc %>%
  separate(sampleDate, c("year", "month", "day"), "-") %>% 
  group_by(Species,year) %>% 
  summarize(ann_count = sum(DailyCount)) %>% 
  group_by(Species) %>% 
  summarize(med_count = median(ann_count))
head(escapement)

```

#Data table

```{r}
datatable(escapement)
```

#Plot the data

```{r}
ggplot(escapement, aes(Species, med_count)) +
  geom_col() +
  coord_flip()+
  labs(y = "Median annual count")+
  theme_bw()
```

#Make map
Datatable
```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
datatable(locations)
```

Use a custom marker so Leaflet doesn't try to grab the marker images from 
its CDN (this was brought up in https://github.com/NCEAS/sasap-training/issues/22)

```{r}
markerIcon <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-icon.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41,
  shadowUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-shadow.png",
  shadowWidth = 41, shadowHeight = 41,
  shadowAnchorX = 13, shadowAnchorY = 41
)
```

#Map!

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location, icon = markerIcon)
```

